name: app_navigator
description: This package helps to manage the navigate between screens in an easy way. A Navigator 2.0 implementation.
version: 0.0.3
repository: https://github.com/vmquintanasnow/app_navigator

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
